CC = gcc
BIN = ./bin
OBJ = ./obj
INC = ./include
SRC = ./src

CFLAGS = -Wall -g -o
ASSEMBLYFLAGS = -c

$(BIN)/duplicateNumbers: $(SRC)/duplicateNumbers.c
	$(CC) $(CFLAGS) $(BIN)/duplicateNumber $(SRC)/duplicateNumbers.c

$(OBJ)/duplicateNumbers.o: $(SRC)/duplicateNumbers.c
	$(CC) $(ASSEMBLYFLAGS) $(OBJ)/duplicateNumbers.o $(SRC)/duplicateNumbers.c
